### ISSUE TITLE
Host it somewhere on line so that anybody can try with just a click?

### ISSUE THREAD

**Issue by Naereen** [kristoffer-dyrkorn/flightsimulator#1]
Hi!
It sounds like a great project!
But for an online app, it's weird to have to clone the project and test it locally.
Could you try to host it somewhere on line so that anybody can try with just a click?
Thanks.

-- 
@Naereen

**Comment by RobertSasak** [comment]
You can use simulator online by visiting http://kristoffer-dyrkorn.github.io/flightsimulator/?n=6722000&e=-33000 .

**Comment by Naereen** [comment]
OK. Thanks. The link should be added to the README.md and maybe the "summary" line (or link) of the project!

**Comment by kristoffer-dyrkorn** [comment]
Fixed now. Thank you!

**Comment by Naereen** [comment]
Looks fixed.
